# Generated by Django 3.2.5 on 2021-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('code_isin', models.CharField(max_length=45)),
                ('symbol', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('listing_date', models.DateField()),
                ('settle_month', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
                ('homepage', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('open', models.CharField(max_length=45)),
                ('close', models.CharField(max_length=45)),
                ('high', models.CharField(max_length=45)),
                ('volume', models.CharField(max_length=45)),
                ('diff', models.CharField(max_length=45)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'stock_price',
            },
        ),
    ]
