# Generated by Django 3.2.6 on 2021-08-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210825_0115'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['code', 'date'], name='stock_price_code_dbf503_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['code'], name='stock_price_code_d0e363_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['date'], name='stock_price_date_f7f9f4_idx'),
        ),
    ]
