# Generated by Django 3.2.6 on 2021-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('code', models.CharField(default='', max_length=45)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'strategy_master',
            },
        ),
        migrations.CreateModel(
            name='StrategyStockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_code', models.CharField(default='', max_length=45)),
                ('ticker', models.CharField(max_length=45)),
                ('rank', models.IntegerField(default=9999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_stock_list',
            },
        ),
        migrations.AddIndex(
            model_name='strategystocklist',
            index=models.Index(fields=['strategy_code'], name='strategy_st_strateg_420fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='strategystocklist',
            index=models.Index(fields=['strategy_code', 'rank'], name='strategy_st_strateg_f62f49_idx'),
        ),
        migrations.AddIndex(
            model_name='strategymaster',
            index=models.Index(fields=['code'], name='strategy_ma_code_826512_idx'),
        ),
    ]
