version: "3.9"
services: 
  webapp:
    build:
      context: .
      dockerfile: ${APP_DOCKFILE}
    environment: 
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    command: /bin/bash ./docker-entrypoint.sh
    ports:
      - ${APP_PORT_EXTERNAL}:${APP_PORT}
    volumes:
      - aistock_prod_web:/app/web
    depends_on: 
      - db
    restart: always
  db:
    image: mysql:${MYSQL_IMAGE_VER}
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT}
    restart: always
volumes:
  aistock_prod_web: