version: "3.9"
services: 
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment: 
      DJANGO_SETTINGS_MODULE: config.settings.local
    command: python manage.py runserver
    ports:
      - 28000:8000
    depends_on: 
      - db
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 23306:3306