# Generated by Django 3.2.6 on 2021-08-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='system_log',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PortfolioStrategyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(default='1000000', max_length=255)),
                ('term', models.CharField(default='1', max_length=255)),
                ('risk', models.CharField(default='30', max_length=255)),
                ('report', models.TextField(default='')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'portfolio_strategy_report',
            },
        ),
    ]
